print('hello long')
require('longnguyen.plugins-setup')
require('longnguyen.core.options')
require('longnguyen.core.keymaps')
require('longnguyen.core.colorscheme')
require('longnguyen.plugins.comment')
require('longnguyen.plugins.nvim-tree')
